export const EFFECTS_WEAR_AND_TEAR = {
    "lwfx_overcharge": "Overcharge",
    "lwfx_overheat_critical_reactor_failure": "Critical Reactor Failure",
    "lwfx_overheat_destabilized_power_plant": "Destabilized Power Plant",
    "lwfx_overheat_emergency_shunt": "Emergency Shunt",
    "lwfx_overheat_irreversible_meltdown": "Irreversible Meltdown",
    "lwfx_overheat_meltdown_3": "Meltdown",
    "lwfx_overheat_meltdown_2": "Meltdown",
    "lwfx_overheat_meltdown_1": "Meltdown",
    "lwfx_overheat_power_failure": "Power Failure",
    "lwfx_stabilize": "Stabilize",
    "lwfx_structure_glancing_blow": "Glancing Blow",
    "lwfx_structure_system_trauma": "Pre System Trauma",
    "lwfx_structure_secondary": "System Trauma",
    "lwfx_structure_direct_hit_3": "Direct Hit 2",
    "lwfx_structure_direct_hit_2": "Direct Hit 2",
    "lwfx_structure_direct_hit_1": "Direct Hit 1",
    "lwfx_structure_crushing_hit": "Crushing Hit",

    // Monstrosity "UNIQUE PHYSIOLOGY" table
    // TODO(Future) implement!
    // "lwfx_monstrosity_fatal": "Monstrosity Fatal Hit",
    // "lwfx_monstrosity_direct_hit_3": "Monstrosity Direct Hit 2",
    // "lwfx_monstrosity_direct_hit_2": "Monstrosity Direct Hit 2",
    // "lwfx_monstrosity_direct_hit_1": "Monstrosity Direct Hit 1",
    // "lwfx_monstrosity_dismember": "Monstrosity Dismemberment",
    // "lwfx_monstrosity_powerful_hit": "Monstrosity Powerful Hit",
    // "lwfx_monstrosity_glancing_hit": "Monstrosity Glancing Hit",
};

export const EFFECTS_GEAR = {
    //NON-ITEM EFFECTS
    "default_tech_attack": "DefaultTech",
    "lwfx_default_melee": "DefaultMelee",
    "lwfx_default_ranged": "Pistol",

    //CORE, LONG RIM, WALLFLOWER, KTB
    "mw_andromeda_pattern_heavy_laser_rifle": "Lasers",
    "mw_annihilation_nexus": "Nexus",
    "mw_annihilator": "Annihilator",
    "mw_anti_materiel_rifle": "AMR",
    "mw_arc_projector": "PPC",
    "mw_assault_cannon": "HMG",
    "mw_assault_rifle": "Assault Rifle",
    "mw_autogun": "Assault Rifle",
    "mw_autopod": "AutoPod",
    "mw_barbarossa_integrated": "Apocalypse Rail",
    "mw_blackspot_targeting_laser": "LockOn",
    "mw_bolt_nexus": "Nexus",
    "mw_bolt_thrower": "Bolt Thrower",
    "mw_bristlecrown_flechette_launcher": "Flechette Launcher",
    "mw_burst_launcher": "Burst Launcher",
    "mw_caliban_integrated": "Shotgun",
    "mw_catalyst_pistol": "Plasma Rifle",
    "mw_catalytic_hammer": "DefaultMelee",
    "mw_chain_axe": "DefaultMelee",
    "mw_charged_blade": "Charged Blade",
    "mw_combat_drill": "Combat Drill",
    "mw_concussion_missiles": "Missile",
    "mw_cutter_mkii_plasma_torch": "Plasma Torch",
    "mw_cyclone_pulse_rifle": "Cyclone Pulse Rifle",
    "mw_d_d_288": "DD 288",
    "mw_daisy_cutter": "Shotgun",
    "mw_deck_sweeper_automatic_shotgun": "Shotgun",
    "mw_displacer": "Displacer",
    "mw_emperor_integrated": "ArcBow",
    "mw_exo_brood_siblings_molt": "Brood Siblings Molt",
    "mw_exo_plasma_maul": "Plasma Maul",
    "mw_exo_steelpunch_heavy_needlebeam": "Needle Beam",
    "mw_exo_sting_heavy_anti_armor_rifle": "AMR",
    "mw_ferrofluid_lance": "War Pike",
    "mw_fold_knife": "DefaultMelee",
    "mw_fuel_rod_gun": "Fuel Rod Gun",
    "mw_fusion_rifle": "Plasma Rifle",
    "mw_gandiva_missiles": "Missile",
    "mw_ghast_nexus": "Nexus",
    "mw_ghoul_nexus": "Nexus",
    "mw_gravity_gun": "Displacer",
    "mw_hammer_u_rpl": "HMG",
    "mw_hand_cannon": "Pistol",
    "mw_heavy_charged_blade": "Charged Blade",
    "mw_heavy_machine_gun": "HMG",
    "mw_heavy_melee_weapon": "DefaultMelee",
    "mw_hhs_155_cannibal": "Shotgun",
    "mw_howitzer": "Mortar",
    "mw_impact_lance": "Impact Lance",
    "mw_impaler_nailgun": "Bolt Thrower",
    "mw_kinetic_hammer": "Hammer",
    "mw_krakatoa_thermobaric_flamethrower": "Flamethrower",
    "mw_kraul_rifle": "Kraul Rifle",
    "mw_lancaster_integrated": "Latch Drone",
    "mw_leviathan_heavy_assault_cannon": "Leviathan",
    "mw_magnetic_cannon": "Impact Lance",
    "mw_mimic_gun": "PPC",
    "mw_missile_rack": "Missile",
    "mw_mortar": "Mortar",
    "mw_nanobot_whip": "Nanobot Whip",
    "mw_nanocarbon_sword": "DefaultMelee",
    "mw_nexus_hunter_killer": "Nexus",
    "mw_nexus_light": "Nexus",
    "mw_oracle_lmg_i": "Assault Rifle",
    "mw_pinaka_missiles": "MissilePinaka",
    "mw_pistol": "Pistol",
    "mw_plasma_thrower": "Plasma Thrower",
    "mw_power_knuckles": "DefaultMelee",
    "mw_prototype_1": "PPC",
    "mw_prototype_2": "PPC",
    "mw_prototype_3": "PPC",
    "mw_rail_rifle": "Railgun",
    "mw_railgun": "Railgun",
    "mw_raleigh_integrated": "Burst Launcher",
    "mw_retort_loop": "Retort Loop",
    "mw_rocket_propelled_grenade": "Missile",
    "mw_segment_knife": "DefaultMelee",
    "mw_sharanga_missiles": "Missiles",
    "mw_shatterhead_colony_missiles": "Missile",
    "mw_sherman_integrated": "Railgun",
    "mw_shock_knife": "DefaultMelee",
    "mw_shotgun": "Shotgun",
    "mw_siege_cannon": "Mortar",
    "mw_slag_cannon": "Slag Cannon",
    "mw_smartgun": "Assault Rifle",
    "mw_sol_pattern_laser_rifle": "Lasers",
    "mw_stub_cannon": "HMG",
    "mw_swarm_hive_nanites": "Nexus",
    "mw_tachyon_lance": "Tachyon Lance",
    "mw_tactical_knife": "DefaultMelee",
    "mw_tactical_melee_weapon": "DefaultMelee",
    "mw_terashima_blade": "DefaultMelee",
    "mw_thermal_lance": "Thermal Rifle",
    "mw_thermal_pistol": "Thermal Rifle",
    "mw_thermal_rifle": "Thermal Rifle",
    "mw_tokugawa_alt_enkidu_integrated": "Plasma Talons",
    "mw_torch": "Torch",
    "mw_unraveler": "Retort Loop",
    "mw_variable_sword": "DefaultMelee",
    "mw_veil_rifle": "Veil Rifle",
    "mw_vijaya_rockets": "Missile",
    "mw_vorpal_gun": "Retort Loop",
    "mw_vulture_dmr": "BattleRifle",
    "mw_war_pike": "War Pike",
    "mw_warp_rifle": "Warp Rifle",
    "mw_xiaoli_combat_sheathe": "DefaultMelee",
    "npcf_acid_spittle_monstrosity": "Nanobot Whip",
    "npcf_anti_armor_weapon_human": "AMR",
    "npcf_anti_armor_weapon_squad": "AMR",
    "npcf_anti_materiel_rifle_sniper": "AMR",
    "npcf_boarding_leash_pirate": "DefaultMelee",
    "npcf_bombard_cannon_bombard": "Apocalypse Rail",
    "npcf_carbon_fiber_sword_ronin": "DefaultMelee",
    "npcf_chain_axe_berserker": "DefaultMelee",
    "npcf_claws_monstrosity": "Plasma Talons",
    "npcf_combat_knife_assault": "DefaultMelee",
    "npcf_combat_shotgun_sentinel": "Shotgun",
    "npcf_concussion_gun_spacer": "Burst Launcher",
    "npcf_demolition_hammer_demolisher": "Hammer",
    "npcf_devils_cough_shotgun_assassin": "Shotgun",
    "npcf_drum_shotgun_goliath": "Shotgun",
    "npcf_dual_shotguns_breacher": "Shotgun",
    "npcf_flak_cannon_engineer": "Mortar",
    "npcf_flamethrower_pyro": "Flamethrower",
    "npcf_flechette_shot_breacher": "Shotgun",
    "npcf_grav_grenade_launcher_seeder": "Displacer",
    "npcf_graviton_lance_barricade": "Warp Rifle",
    "npcf_gravity_rifle_spacer": "Warp Rifle",
    "npcf_harpoon_cannon_berserker": "ArcBow",
    "npcf_heated_blade_assassin": "DefaultMelee",
    "npcf_heavy_assault_rifle_assault": "Assault Rifle",
    "npcf_heavy_assault_shield_bastion": "DefaultMelee",
    "npcf_hellfire_projector_ultra": "Annihilator",
    "npcf_hex_missiles_hornet": "Missile",
    "npcf_hunter_killer_nexus_hive": "Nexus",
    "npcf_light_laser_aegis": "Lasers",
    "npcf_light_machine_gun_archer": "HMG",
    "npcf_machine_pistol_specter": "Pistol",
    "npcf_marker_rifle_scout": "LockOn",
    "npcf_melee_weapon_human": "DefaultMelee",
    "npcf_missile_launcher_ace": "Missile",
    "npcf_missile_pods_rainmaker": "Missiles",
    "npcf_missile_swarm_ace": "Missiles",
    "npcf_monowire_sword_specter": "DefaultMelee",
    "npcf_nail_gun_berserker": "Kraul Rifle",
    "npcf_napalm_bomb_pyro": "Mortar",
    "npcf_nova_missiles_operator": "Missile",
    "npcf_primary_weapon_squad": "Assault Rifle",
    "npcf_pulse_laser_scourer": "Veil Rifle",
    "npcf_ram_cannon_cataphract": "DefaultMelee",
    "npcf_ranged_weapon_human": "Pistol",
    "npcf_raptor_plasma_rifle_operator": "Plasma Rifle",
    "npcf_ravager_turret_ultra": "HMG",
    "npcf_repeater_cannon_bombard": "Mortar",
    "npcf_retractable_sword_sentinel": "DefaultMelee",
    "npcf_rotary_grenade_launcher_bastion": "Mortar",
    "npcf_seeker_cloud_hive": "Nexus",
    "npcf_stinger_pistol_hornet": "Pistol",
    "npcf_thermal_lance_scourer": "Thermal Rifle",
    "npcf_underslung_grenade_launcher_assault": "Mortar",
    "nrfaw-npc_npcf_judgement_shotgun_avenger": "Shotgun",
    "nrfaw-npc_npcf_marksman_kit_ranger_long_rifle_strider": "AMR",
    "nrfaw-npc_npcf_ripper_claws_lurker": "Nanobot Whip",
    "nrfaw-npc_npcf_sapper_kit_mag_shotgun_strider": "Shotgun",
    "nrfaw-npc_npcf_scouring_whip_lurker": "Nanobot Whip",
    "nrfaw-npc_npcf_siege_kit_shoulder_mortar_strider": "Mortar",
    "nrfaw-npc_npcf_skirmisher_kit_explosive_rifle_strider": "Bolt Thrower",
    "nrfaw-npc_npcf_slug_pistol_avenger": "Pistol",

    //SOLSTICE RAIN
    "mw_xc_br_battle_rifle": "BattleRifle",
    "mw_xc_dpm_predator_nexus": "Nexus",

    //WINTER SCAR
    "mw_shrapnel_cannon": "Shrapnel Cannon",
    "mw_fusion_torch": "Plasma Torch",
    "mw_superthermal_blade": "Charged Blade",
    "mw_integrated_shock_claws": "Shock Claws",
    "npc_mbt_smoothbore_cannon": "Apocalypse Rail",
    "npc_mbt_railgun": "Railgun",
    "npc_mbt_antares-pattern_laser_cannon": "Lasers",
    "npc_mbt_anti-tank_gun": "Apocalypse Rail",
    "npc_mbt_streetsweeper_canister_projector": "CannonAirburst",
    "npc_mbt_pintle-mounted_machine_gun": "HMG",
    "npc_mbt_anti-armor_missiles": "Missile",
    "npc_mbt_marker_nexus": "Nexus",
    "npc_mbt_skylight_anti-air_laser": "Lasers",
    "npc_mbt_multi-directional_charges": "Flechette Launcher",

    //DUSTGRAVE
    "mw_blast_pick": "BlastPick",
    "mw_brutus_shield": "DefaultMelee",
    "mw_brutus_wrecker": "DefaultMelee",
    "mw_hurricane_cluster_projector": "CannonAirburst",
    "mw_reaper_assault_cannon": "Leviathan",
    "mw_shock_baton": "ShockBaton",
    "mw_tempest_charged_blade": "TempestBlade",

    //DUSTGRAVE NPCs
    "npcf_assimilaiton_maw_horror": "AssimilationMaw",
    "npcf_buzzsaw_industrial_mech": "DefaultMelee",
    "npcf_disruptor_whip_horror": "DisruptorWhip",
    "npcf_fusion_cutter_industrial_mech": "Plasma Torch",
    "npcf_gyrojet_cannon_spec_op": "Missile",
    "npcf_industrial_clamps_industrial_mech": "DefaultMelee",
    "npcf_rivet_cannon_industrial_mech": "Bolt Thrower",
    "npcf_rock_drill_industrial_mech": "Combat Drill",
    "npcf_serrated_machete_spec_op": "DefaultMelee",
    "npcf_wrecker_industrial_mech": "DefaultMelee",

    //SIRENS SONG
    "npc_Leech_PairedTalonsMKII": "Plasma Talons",
    "npc_PDCTurret": "Leviathan",
    "npc_Tempest_NaniteMonsoonDispensers": "Nexus",
    "npc_Tempest_TyphoonNaniteCannon": "Nexus",

    //NPC REBAKE
    "npc-rebake_npcf_missile_launcher_ace": "Missile",
    "npc-rebake_npcf_missile_swarm_ace": "Missiles",
    "npc-rebake_npcf_light_laser_aegis": "Lasers",
    "npc-rebake_npcf_light_machine_gun_archer": "HMG",
    "npc-rebake_npcf_heated_blade_assassin": "DefaultMelee",
    "npc-rebake_npcf_devils_cough_shotgun_assassin": "Shotgun",
    "npc-rebake_npcf_weapon_heavy_assault": "Assault Rifle",
    "npc-rebake_npcf_weapon_combat_knife": "DefaultMelee",
    "npc-rebake_npcf_weapon_underslung_grenade": "Mortar",
    "npc-rebake_npcf_graviton_lance_barricade": "Warp Rifle",
    "npc-rebake_npcf_rotary_grenade_launcher_bastion": "Mortar",
    "npc-rebake_npcf_heavy_assault_shield_bastion": "DefaultMelee",
    "npc-rebake_npcf_chain_axe_berserker": "DefaultMelee",
    "npc-rebake_npcf_harpoon_cannon_berserker": "ArcBow",
    "npc-rebake_npcf_bombard_cannon_bombard": "Apocalypse Rail",
    "npc-rebake_npcf_dual_shotguns_breacher": "Shotgun",
    "npc-rebake_npcf_ram_cannon_cataphract": "DefaultMelee",
    "npc-rebake_npcf_demolition_hammer_demolisher": "Hammer",
    "npc-rebake_npcf_earthshatter_demolisher": "Hammer",
    "npc-rebake_npcf_flak_cannon_engineer": "Mortar",
    "npc-rebake_npcf_drum_shotgun_goliath": "Shotgun",
    "npc-rebake_npcf_hunter_killer_nexus_hive": "Nexus",
    "npc-rebake_npcf_stinger_pistol_hornet": "Pistol",
    "npc-rebake_npcf_raptor_plasma_rifle_operator": "Plasma Rifle",
    "npc-rebake_npcf_flamethrower_pyro": "Flamethrower",
    "npc-rebake_npcf_missile_pods_rainmaker": "Missiles",
    "npc-rebake_npcf_carbon_fiber_sword_ronin": "DefaultMelee",
    "npc-rebake_npcf_thermal_lance_scourer": "Thermal Rifle",
    "npc-rebake_npcf_marker_rifle_scout": "LockOn",
    "npc-rebake_npcf_grav_grenade_launcher_seeder": "Displacer",
    "npc-rebake_npcf_combat_shotgun_sentinel": "Shotgun",
    "npc-rebake_npcf_retractable_sword_sentinel": "DefaultMelee",
    "npc-rebake_npcf_anti_materiel_rifle_sniper": "AMR",
    "npc-rebake_npcf_monowire_sword_specter": "DefaultMelee",
    "npc-rebake_npcf_machine_pistol_specter": "Pistol",
    "npc-rebake_npcf_dmr_artillery_grunt": "AMR",
    "npc-rebake_npcf_shoulder_mortar_artillery_grunt": "Mortar",
    "npc-rebake_npcf_survival_pistol_artillery_grunt": "Pistol",
    "npc-rebake_npcf_shotgun_defender_grunt": "Shotgun",
    "npc-rebake_npcf_assault_rifle_striker_grunt": "Assault Rifle",
    "npc-rebake_npcf_heavy_blade_striker_grunt": "DefaultMelee",
    "npc-rebake_npcf_hellfire_projector_ultra": "Annihilator",
    "npc-rebake_npcf_hyperdense_blade_ultra": "DefaultMelee",
    "npc-rebake_npcf_miniaturized_railgun_ultra": "Railgun",
    "npc-rebake_npcf_nova_missiles_ultra": "Missiles",
    "npc-rebake_npcf_ravager_turret_ultra": "HMG",
    "npc-rebake_npcf_wraith_nexus_ultra": "Nexus",
    "nrfaw-npc-rebake_npcf_judgement_shotgun_avenger": "Shotgun",
    "nrfaw-npc-rebake_npcf_scouring_whip_lurker": "Nanobot Whip",
    "nrfaw-npc-rebake_npcf_slug_pistol_avenger": "Pistol",
    "nrfaw-npc-rebake_npcf_marksman_kit_ranger_long_rifle_strider": "AMR",
    "nrfaw-npc-rebake_npcf_skirmisher_kit_explosive_carbine_strider": "Bolt Thrower",
    "nrfaw-npc-rebake_npcf_survival_knife_strider": "DefaultMelee",

    //HEURISTICS
    "lwfx_heuristic_melee": "DefaultMelee",
    "lwfx_heuristic_cqb_energy": "PPC",
    "lwfx_heuristic_cqb_shotgun": "Shotgun",
    "lwfx_heuristic_cqb_other": "Pistol",
    "lwfx_heuristic_cannon_energy": "Tachyon Lance",
    "lwfx_heuristic_cannon_mg": "HMG",
    "lwfx_heuristic_cannon_other": "Mortar",
    "lwfx_heuristic_launcher": "Missile",
    "lwfx_heuristic_nexus": "Nexus",
    "lwfx_heuristic_rifle_energy": "Thermal Rifle",
    "lwfx_heuristic_rifle_mg": "HMG",
    "lwfx_heuristic_rifle_ar": "Assault Rifle",
    "lwfx_heuristic_rifle_other": "AMR",

    //CASTOR & POLLUX PCs
    "cap_apothecary_marksman_rifle": "AMR",
    "cap_bulkhead_auger": "Veil Rifle",
    "cap_corona_purge": "PPC",
    "cap_dazzler": "PPC",
    "cap_demisolar_lens": "Veil Rifle",
    "cap_dispersal_bow": "Bolt Thrower",
    "cap_flintlock_pistol": "Thermal Rifle",
    "cap_furnace_hammer": "Hammer",
    "cap_geoform_wrecking_ball": "BlastPick",
    "cap_grim_harvest_plasma_scythe": "Nanobot Whip",
    "cap_grinder_combat_uzi": "Assault Rifle",
    "cap_micro_mass_driver": "Railgun",
    "cap_plasma_caster": "Plasma Torch",
    "cap_riptide_ballistic_harpoon": "Kraul Rifle",
    "cap_shriek_rifle": "Impact Lance",
    "cap_snap_crush_mining_jaws": "DefaultMelee",
    "cap_tt32_glacier_lake_coolant_hose": "Slag Cannon",
    "cap_tt8_alpine_spring_carbine": "AMR",
    "cap_typhoon_channel": "Annihilator",
    "cap_voltaic_swarm": "PPC",
    "cap_wildfire_missiles": "Missiles",
    "mw_tametomo_integrated": "ArcBow",

    //CASTOR & POLLUX NPCs
    "cap_npc_architect_slurry_cannon": "Slag Cannon",
    "cap_npc_grenadier_taiko_gl_16": "Mortar",
    "cap_npc_grenadier_short_fuses": "PPC",
    "cap_npc_interceptor_interdiction_smg": "HMG",
    "cap_npc_packmaster_tracer_rifle": "Needle Beam",
    "cap_npc_packmaster_hex_drone": "Annihilator",
    "cap_npc_packmaster_killshot": "AMR",
    "cap_npc_pyre_fuel_rod_sling": "Fuel Rod Gun",
    "cap_npc_vector_widowmaker_long_rifle": "Kraul Rifle",
    "cap_npc_vector_burst_silos": "MissilePinaka",

    //DEPLOYABLE TURRETS
    "engiturret_attack": "Assault Rifle",
    "engiturret_hellstorm": "Missiles",
    "engiturret_hunter": "AMR",
    "engiturret_inferno": "Flamethrower",

    //ENHANCED COMBAT NPCs
    "npcf_integrated_launch_tubes_behemoth": "Missiles",
    "npcf_titanic_stomping_behemoth": "BlastPick",
    "npcf_slinger_cannon_train": "Mortar",
    "npcf_mauler_carbine_contract_killer": "Kraul Rifle",
    "npcf_hunting_knife_contract_killer": "Charged Blade",
    "npcf_drain_beam_amplifier": "Retort Loop",
    "npcf_meaty_fists_brute": "DefaultMelee",
    "npcf_grafted_weapon_brute": "Assault Rifle",
    "npcf_longsword_crusader": "DefaultMelee",
    "npcf_tower_shield_crusader": "DefaultMelee",
    "npcf_executioners_blade_executioner": "DefaultMelee",
    "npcf_meathook_executioner": "War Pike",
    "npcf_gutpunch_executioner": "BlastPick",
    "npcf_mortar_array_fortress": "Apocalypse Rail",
    "npcf_carbine_with_bayonet_legionnaire": "BattleRifle",
    "npcf_lazarus_nexus_necromancer": "PPC",
    "npcf_the_bite_nosferatu": "AssimilationMaw",
    "npcf_superheated_talons_nosferatu": "Plasma Talons",
    "npcf_prism_rifle_phantasm": "Retort Loop",

    //FIELD GUIDE TO STELLAR VOID PCs
    "fgttsv_weapons_chain_dart": "Kraul Rifle",
    "fgttsv_weapons_dento_heavy_blade": "Charged Blade",
    "fgttsv_weapons_minimally_audible_carbine_system": "Tachyon Lance",
    "fgttsv_weapons_pump_action_core_shotgun": "Fuel Rod Gun",

    //FIELD GUIDE TO SULDAN PCs
    "fgtsmw_exo_firehawk": "",
    "fgtsmw_anti_armor_missile": "MissilePinaka",
    "fgtsmw_apex_nexus": "PPC",
    "fgtsmw_assault_shotgun": "Shotgun",
    "fgtsmw_anti_cavalry_melee": "War Pike",
    "fgtsmw_light_machine_gun": "HMG",
    "fgtsmw_wasp_nexus": "Nexus",
    "fgtsmw_warthog_gpmg": "Leviathan",
    "fgtsmw_ballistic_shield": "DefaultMelee",
    "fgtsmw_mk_12_chassis_served_support_weapon": "AMR",
    "fgtsmw_sticky_launcher": "Mortar",
    "fgtsmw_archer_nexus": "Missile",
    "fgtsmw_colony_nexus": "Assault Rifle",
    "fgtsmw_govardhana_micromissiles": "Missile",
    "fgtsmw_harrier_nexus": "HMG",
    "fgtsmw_teen_baan_missiles": "Missiles",
    "fgtsmw_vayavya_missiles": "MissilePinaka",
    "fgtsmw_qublade": "Charged Blade",
    "fgtsmw_seeker_catapult": "Tachyon Lance",
    "fgtsmw_slipgun": "Displacer",
    "fgtsmw_advanced_combat_rifle_modular": "Assault Rifle",
    "fgtsmw_kinesis_driver": "Railgun",
    "fgtsmw_orion_pattern_hotshot_laser": "Lasers",
    "fgtsmw_onager_combat_shotgun": "Shotgun",
    "fgtsmw_polaris_pattern_multifunction_laser": "Plasma Rifle",
    "fgtsmw_banderilla_anti_radiation_missiles": "MissilePinaka",
    "fgtsmw_blast_chain": "DefaultMelee",
    "fgtsmw_electropasma_shield": "DefaultMelee",
    "fgtsmw_khetaka_heavy_combat_shield": "BlastPick",
    "fgtsmw_macuahuitl_chainsword": "Charged Blade",
    "fgtsmw_motorized_tetsubo": "BlastPick",
    "fgtsmw_peregrine_seeker_glaive": "AutoPod",
    "fgtsmw_remote_targeting_relay": "Thermal Rifle",
    "fgtsmw_salamander_incendiary_shotgun": "Veil Rifle",
    "fgtsmw_scavenger_nexus": "Nexus",
    "fgtsmw_shock_lash": "ShockBaton",
    "fgtsmw_shroud_missiles": "Missile",
    "fgtsmw_sirocco_machine_pistol": "Pistol",
    "fgtsmw_slug_gun": "AMR",
    "fgtsmw_smartblade": "DefaultMelee",
    "fgtsmw_tangler_cannon": "Warp Rifle",
    "fgtsmw_tiger_claws": "Plasma Talons",
    "fgtsmw_type_17_boarding_pistol": "Pistol",
    "fgtsmw_type_96_shield_gun": "AMR",
    "fgtsmw_viral_knife": "ShockBaton",
    "fgtsmw_chimera_integrated": "PPC",
    "fgtsmw_gajasura_integrated": "DefaultMelee",
    "fgtsmw_kallarani_integrated": "CannonAirburst",
    "fgtsmw_sagittarius_integrated": "ArcBow",

    //FIELD GUIDE TO SULDAN NPCs
    "npc_carrier_RemoteMachineGun": "HMG",
    "npc_carrier_AGL": "Mortar",
    "npc_conscript_AAD": "BlastPick",
    "npc_conscript_DisposablePDW": "HMG",
    "npc_conscript_MilitiaRifle": "Assault Rifle",
    "npc_gladiator_BreachingDrill": "Combat Drill",
    "npc_gladiator_MaulFist": "DD 288",
    "npc_gladiator_SpikedShield": "DefaultMelee",
    "npc_gladiator_TorqueFlail": "Hammer",
    "npc_nightmare_FugueState": "PPC",
    "npc_nightmare_ParalyticEngram": "PPC",
    "npc_nightmare_EphialtesStrain": "DisruptorWhip",
    "npc_nightmare_InductiveTalons": "Plasma Talons",
    "npc_ogre_ImpactGauntlets": "BlastPick",
    "npc_phantom_PhaseBlade": "TempestBlade",
    "npc_reaver_DisplacementLash": "Nanobot Whip",
    "npc_sergeant_AssaultCarbine": "BattleRifle",
    "npc_termite_LaserDrill": "Impact Lance",
    "npc_titan_FLB": "Mortar",
    "npc_titan_SpinalLance": "Annihilator",
    "npc_titan_PDA": "HMG",
    "npc_valkyrie_NanocarbonPartizan": "DefaultMelee",
    "npc_scrapper_MountedTurret": "Assault Rifle",
    "npc_scrapper_SalvagedAutocannon": "Bolt Thrower",
    "npc_scrapper_Piledriver": "BlastPick",

    //Frontline NPCs
    "fl_npcf_hailstorm_dual_gatlings": "HMG",
    "fl_npcf_legion_pilum": "PPC",
    "fl_npcf_legion_toxos": "Annihilator",
    "fl_npcf_light_fusion": "Impact Lance",
    "fl_npcf_railcannon": "Railgun",
    "fl_npcf_soldier_repeaters": "Assault Rifle",
    "fl_npcf_tempest_catapult": "MissilePinaka",

    //GMS CRISIS CORE PCs
    "GMSC_weapons_anti-ship_missile": "MissilePinaka",
    "GMSC_weapons_anti-tank_guided_missile": "Missile",
    "GMSC_weapons_autocannon": "AMR",
    "GMSC_weapons_deluge_missiles": "Missiles",
    "GMSC_weapons_fragmentation_launcher": "CannonAirburst",
    "GMSC_weapons_grenade_launcher": "Mortar",
    "GMSC_weapons_heavy_slug_shotgun": "AMR",
    "GMSC_weapons_helios_nexus": "Nexus",
    "GMSC_weapons_magna_ferrum": "Kraul Rifle",
    "GMSC_weapons_nexus_(apex_hunter)": "Nexus",
    "GMSC_weapons_recoilless_rifle": "Railgun",
    "GMSC_weapons_ultraheavy_combat_maul": "BlastPick",

    //GMS CRISIS CORE NPCs
    "gmsccc_npcf_hydraulic_claw_jaguar": "Plasma Talons",
    "gmsccc_npcf_service_maul_jumper": "DefaultMelee",
    "gmsccc_npcf_meteor_cannons_jumper": "HMG",
    "gmsccc_npcf_ripjaw_shotgun_pointman": "Shotgun",
    "gmsccc_npcf_entrenching_tool_pointman": "DefaultMelee",
    "gmsccc_npcf_marksman_morphogun_sorcerer": "BattleRifle",
    "gmsccc_npcf_ranger_morphogun_sorcerer": "Impact Lance",
    "gmsccc_npcf_spearhead_morphogun_sorcerer": "AMR",
    "gmsccc_npcf_hacksaw_chain_gun_sentry": "HMG",
    "gmsccc_npcf_yellow_jacket_launcher_sentry": "MissilePinaka",
    "gmsccc_npcf_riot_cannon_enforcer": "Shotgun",
    "gmsccc_npcf_zeus_pile_bunker_fulgaraton_enforcer": "BlastPick",
    "gmsccc_npcf_crew_magnetic_rifle_squadron": "Railgun",
    "gmsccc_npcf_typhoon_launcher_squadron": "Missiles",
    "gmsccc_npcf_broadsweep_array_squadron": "Thermal Rifle",
    "gmsccc_npcf_heavy_mortars_squadron": "Mortar",
    "gmsccc_npcf_heavy_javelin_squadron": "War Pike",
    "gmsccc_npcf_chassis_defense_weapon_squadron": "PPC",
    "gmsccc_npcf_smoke_pistol_squadron": "Mortar",
    "gmsccc_npcf_service_knife_squadron": "DefaultMelee",
    "gmsccc_npcf_auto-turret_squadron": "HMG",
    "gmsccc_npcf_grenadier_special_squadron": "Bolt Thrower",
    "gmsccc_npcf_monsoon_rotary_cannon_gunship": "Leviathan",
    "gmsccc_npcf_recoilless_heavy_grenade_launcher_gunship": "CannonAirburst",
    "gmsccc_npcf_multi-ordnance-projectile_cannon_gunship": "Bolt Thrower",
    "gmsccc_npcf_positron_lance_gunship": "Annihilator",
    "gmsccc_npcf_recoilless_howitzer_gunship": "Mortar",
    "gmsccc_npcf_thunderhead_gams_gunship": "Missile",
    "gmsccc_npcf_venator_agm_gunship": "MissilePinaka",
    "gmsccc_npcf_incendiary_vrs_gunship": "Missile",
    "gmsccc_npcf_eclipse_laser_projector_lifter": "Thermal Rifle",
    "gmsccc_npcf_atas_missiles_lifter": "Missile",
    "gmsccc_npcf_long_gun_cavalier": "Railgun",
    "gmsccc_npcf_cdw_cavalier": "Tachyon Lance",
    "gmsccc_npcf_combat_maul_cavalier": "DefaultMelee",
    "gmsccc_npcf_howitzer_cavalier": "Mortar",
    "gmsccc_npcf_rocket_pods_cavalier": "Missiles",
    "gmsccc_npcf_anti-tank_lance_cavalier": "Impact Lance",
    "gmsccc_npcf_war_maul_cavalier": "Hammer",
    "gmsccc_npcf_shock_cdw_cavalier": "PPC",
    "gmsccc_npcf_envenom_cavalier": "DisruptorWhip",

    //MANUFACTURER TEMPLATES
    "npcf_ha_breach_rifle": "Displacer",
    "npcf_ha_unfold_tesseract": "Warp Rifle",
    "npcf_horus_hunter_swarm": "Nexus",
    "npcf_horus_sealing_rite": "Retort Loop",
    "npcf_horus_time_stop": "Retort Loop",
    "npcf_ipsn_pilebunker": "BlastPick",
    "npcf_ssc_nova_rocket": "Missile",

    //MAXIMUM THREAT
    "npcf_nanite_launcher_catapult_maxt": "Railgun",
    "npcf_signature_sidearm_specialist_maxt": "Pistol",
    "npcf_ares_7_battle_rifle_specialist_maxt": "Assault Rifle",
    "npcf_anti_armor_rifle_specialist_maxt": "AMR",
    "npcf_luck_siphon_curse_maxt": "Retort Loop",
    "npcf_beacon_rifle_curse_maxt": "Displacer",
    "npcf_hostage_link_system_warlock_maxt": "Retort Loop",
    "npcf_sabotage_munitions_warlock_maxt": "PPC",
    "npcf_matter_whip_warlock_maxt": "DisruptorWhip",
    "npcf_displacement_beam_warlock_maxt": "Warp Rifle",
    "npcf_thumper_zoner_maxt": "Mortar",
    "npcf_nudge_missile_zoner_maxt": "MissilePinaka",
    "npcf_heatwave_flamethrower_arsonist_maxt": "Flamethrower",
    "npcf_plasma_launcher_arsonist_maxt": "Burst Launcher",
    "npcf_air_boss_flak_cannon_cannonade_maxt": "Mortar",
    "npcf_shredder_cannons_cannonade_maxt": "HMG",
    "npcf_anti_ship_charge_rail_cannonade_maxt": "Annihilator",
    "npcf_strike_trident_pawn_maxt": "War Pike",
    "npcf_riot_gun_pawn_maxt": "Shotgun",
    "npcf_gravity_lance_dragoon_maxt": "Warp Rifle",
    "npcf_dual_jethro_submachineguns_dragoon_maxt": "HMG",
    "npcf_monofilament_rapier_fencer_maxt": "DefaultMelee",
    "npcf_dueling_pistol_fencer_maxt": "Pistol",
    "npcf_reinforced_strike_pylons_monk_maxt": "DefaultMelee",
    "npcf_electric_tonfa_monk_maxt": "ShockBaton",
    "npcf_reactor_rod_cannon_freezer_maxt": "Fuel Rod Gun",
    "npcf_perimeter_defense_cannon_logistic_maxt": "HMG",
    "npcf_gravity_maul_super_maxt": "DD 288",
    "npcf_annihilation_pulse_super_maxt": "Annihilator",
};
